# Generated by Django 5.1.4 on 2025-01-03 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default='culture', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img/empty.png', upload_to='img/'),
        ),
    ]
